### ISSUE TITLE
起動しなかった

### ISSUE THREAD

**Issue by kotarobo** [SakuraServerDevTeam/FlagGame#12]
[22:18:15] [Server thread/INFO]: [FlagGame] Enabling FlagGame v2.0-alpha11
[22:18:15] [Server thread/WARN]: [FlagGame] World flag is Not Found! Disabling plugin..
[22:18:15] [Server thread/INFO]: [FlagGame] Disabling FlagGame v2.0-alpha11
[22:18:15] [Server thread/ERROR]: Error occurred while disabling FlagGame v2.0-alpha11 (Is it up to date?)
java.lang.NullPointerException
    at syam.flaggame.FlagGame.onDisable(FlagGame.java:195) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot.jar:git-Spigot-fdc1440-53fac9f]
    at syam.flaggame.ConfigurationManager.loadConfig(ConfigurationManager.java:146) [FlagGame-2.0-alpha11.jar:?]
    at syam.flaggame.FlagGame.onEnable(FlagGame.java:113) [FlagGame-2.0-alpha11.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-fdc1440-53fac9f]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-fdc1440-53fac9f]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-fdc1440-53fac9f]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-fdc1440-53fac9f]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-fdc1440-53fac9f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-fdc1440-53fac9f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-fdc1440-53fac9f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-fdc1440-53fac9f]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-fdc1440-53fac9f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot.jar:git-Spigot-fdc1440-53fac9f]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[22:18:15] [Server thread/INFO]: [FlagGame] Hooked to Vault!

**Comment by 4oi** [comment]
[22:18:15] [Server thread/WARN]: [FlagGame] World flag is Not Found! Disabling plugin..
flagというワールドがない旨のエラーです
NPEは修正対象ですが...
