### ISSUE TITLE
Error occurred while enabling FlagGame v2.0-beta6

### ISSUE THREAD

**Issue by 4oi** [SakuraServerDevTeam/FlagGame#30]
```
[19:35:26] [Server thread/INFO]: [FlagGame] Enabling FlagGame v2.0-beta6
[19:35:26] [Server thread/INFO]: [FlagGame] Hooked to Vault!
[19:35:26] [Server thread/INFO]: [FlagGame] Using Vault: PermissionsEx for permissions
[19:35:26] [Server thread/ERROR]: Error occurred while enabling FlagGame v2.0-beta6 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event org.bukkit.event.player.PlayerEvent. Static getHandlerList method required!
 at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:586) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
 at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:584) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
 at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:528) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
 at syam.flaggame.FlagGame.lambda$registerListeners$3(FlagGame.java:310) ~[?:?]
 at syam.flaggame.FlagGame$$Lambda$212/1985749157.accept(Unknown Source) ~[?:?]
 at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51]
 at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51]
 at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_51]
 at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
 at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
 at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51]
 at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51]
 at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
 at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51]
 at syam.flaggame.FlagGame.registerListeners(FlagGame.java:310) ~[?:?]
 at syam.flaggame.FlagGame.onEnable(FlagGame.java:146) ~[?:?]
 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at com.jadeningle.PluginManager.Utils.Control.enablePlugin(Control.java:79) [PluginManager-Reloaded-1.0.0.jar:?]
 at com.jadeningle.PluginManager.pluginManagerCommand.loadPluginCommand(pluginManagerCommand.java:161) [PluginManager-Reloaded-1.0.0.jar:?]
 at com.jadeningle.PluginManager.pluginManagerCommand.onCommand(pluginManagerCommand.java:59) [PluginManager-Reloaded-1.0.0.jar:?]
 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[19:35:26] [Server thread/INFO]: [0;32;1mFlagGame 2.0-beta6 loaded![m
[19:35:29] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to FlagGame v2.0-beta6
org.bukkit.event.EventException
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
 at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
 at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
 at syam.flaggame.listener.FGPlayerListener.onPlayerInteract(FGPlayerListener.java:71) ~[?:?]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
 at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
 ... 17 more
```

**Comment by toyblocks** [comment]
https://github.com/SakuraServerDevTeam/FlagGame/tree/1b34387c3ff9bc4b6a21085783afdbc568a32748
