### ISSUE TITLE
同点でおかしくなる。エラー？

### ISSUE THREAD

**Issue by kotarobo** [SakuraServerDevTeam/FlagGame#32]
同点時(試合終了時がフラグかもしれない)
にエラーが出て募集をかけても既に別の試合に参加していることになっていて参加できない

**Comment by 4oi** [comment]
ごめんなさい，エラーログがないと問題箇所が把握できませんでした．
エラーログとともに再報告をお願いします．

**Comment by kotarobo** [comment]
[20:39:47] [Server thread/INFO]: kotarobo_ issued server command: /f start
[20:39:55] [Server thread/INFO]: XoKONOHAoX issued server command: /f join
[20:40:02] [Server thread/WARN]: [FlagGame] Task #75757 for FlagGame v2.0-beta11 generated an exception
java.lang.IllegalArgumentException: That player is not joined
    at jp.llv.flaggame.reception.RealtimeTeamingReception.leave(RealtimeTeamingReception.java:176) ~[?:?]
    at syam.flaggame.player.GamePlayer.leave(GamePlayer.java:112) ~[?:?]
    at jp.llv.flaggame.reception.RealtimeTeamingReception.close(RealtimeTeamingReception.java:116) ~[?:?]
    at jp.llv.flaggame.game.basic.BasicGame.stop(BasicGame.java:329) ~[?:?]
    at jp.llv.flaggame.game.basic.BasicGame$$Lambda$1104/1884075482.run(Unknown Source) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by kotarobo** [comment]
[20:46:48] [Server thread/WARN]: [FlagGame] Task #138 for FlagGame v2.0-beta11 generated an exception
java.lang.IllegalArgumentException: That player is not joined
    at jp.llv.flaggame.reception.RealtimeTeamingReception.leave(RealtimeTeamingReception.java:176) ~[?:?]
    at syam.flaggame.player.GamePlayer.leave(GamePlayer.java:112) ~[?:?]
    at jp.llv.flaggame.reception.RealtimeTeamingReception.close(RealtimeTeamingReception.java:116) ~[?:?]
    at jp.llv.flaggame.game.basic.BasicGame.stop(BasicGame.java:329) ~[?:?]
    at jp.llv.flaggame.game.basic.BasicGame$$Lambda$90/1318299905.run(Unknown Source) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by kotarobo** [comment]
[20:51:47] [Server thread/WARN]: [FlagGame] Task #308 for FlagGame v2.0-beta12 generated an exception
java.lang.IllegalArgumentException: That player is not joined
    at jp.llv.flaggame.reception.RealtimeTeamingReception.leave(RealtimeTeamingReception.java:176) ~[?:?]
    at syam.flaggame.player.GamePlayer.leave(GamePlayer.java:112) ~[?:?]
    at jp.llv.flaggame.reception.RealtimeTeamingReception.close(RealtimeTeamingReception.java:116) ~[?:?]
    at jp.llv.flaggame.game.basic.BasicGame.stop(BasicGame.java:329) ~[?:?]
    at jp.llv.flaggame.game.basic.BasicGame$$Lambda$187/1794438800.run(Unknown Source) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by 4oi** [comment]
https://github.com/SakuraServerDevTeam/FlagGame/commit/6f7a1348b8061d272f030aaf72f77d38976255e5
