### ISSUE TITLE
NoSuchElementException while rollback

### ISSUE THREAD

**Issue by 4oi** [SakuraServerDevTeam/FlagGame#60]
```
java.util.NoSuchElementException
        at java.util.LinkedList.getFirst(LinkedList.java:244) ~[?:1.8.0_121]
        at jp.llv.flaggame.rollback.QueuedSerializeTask.step(QueuedSerializeTask.java:36) ~[?:?]
        at jp.llv.flaggame.rollback.SerializeTask.run(SerializeTask.java:49) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-b605b31-f4822eb]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-b605b31-f482]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-b605b31-f4822eb]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-b605b31-f4822eb]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-b605b31-f4822eb]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-b605b31-f4822eb]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

```

**Comment by 4oi** [comment]
発生条件について追加の検証が必要
